import type { Project } from '@/types'

const LOCAL_PROJECTS: Project[] = [
  {
    id: 'p-short-001',
    title: 'Mini CLI Utilities',
    slug: 'mini-cli-utilities',
    description: 'A collection of small developer CLI tools and helpers for productivity.',
    content: null,
    tags: ['tools', 'cli'],
    image_url: null,
    demo_url: null,
    github_url: null,
    status: 'completed',
    contributors: null,
    is_published: true,
    created_at: '2025-11-01T00:00:00Z',
  },

  // Medium projects
  {
    id: 'p-med-001',
    title: 'Newton Bot (RAG Practice Generator)',
    slug: 'newton-bot',
    description: 'A retrieval-augmented generator trained on our college slides to produce accurate practice problem sets for students.',
    content: null,
    tags: ['ai', 'rag', 'education'],
    image_url: null,
    demo_url: null,
    github_url: null,
    status: 'completed',
    contributors: null,
    is_published: true,
    created_at: '2026-01-12T00:00:00Z',
  },
  {
    id: 'p-med-002',
    title: 'RLM Research Experiment',
    slug: 'rlm-research',
    description: 'A research experiment evaluating state-of-the-art RLMs on benchmark tasks and diagnostics.',
    content: null,
    tags: ['research', 'rlm'],
    image_url: null,
    demo_url: null,
    github_url: null,
    status: 'ongoing',
    contributors: null,
    is_published: true,
    created_at: '2026-02-01T00:00:00Z',
  },

  // Long projects
  {
    id: 'p-long-001',
    title: 'Divuze — Fashion Tech Try-On Hardware',
    slug: 'divuze-fashion-tech',
    description: 'Divuze builds a hardware + software system to superimpose clothes in real-time, replacing changing-room wait times with AR try-on.',
    content: null,
    tags: ['fashion', 'hardware', 'ar'],
    image_url: null,
    demo_url: null,
    github_url: null,
    status: 'ongoing',
    contributors: null,
    is_published: true,
    created_at: '2025-08-15T00:00:00Z',
  },
  {
    id: 'p-long-002',
    title: 'AI for Energy Transmission (Policy)',
    slug: 'ai-energy-policy',
    description: 'A cross-disciplinary project exploring AI tools and policy frameworks for efficient energy transmission.',
    content: null,
    tags: ['policy', 'energy', 'ai'],
    image_url: null,
    demo_url: null,
    github_url: null,
    status: 'ongoing',
    contributors: null,
    is_published: true,
    created_at: '2025-09-20T00:00:00Z',
  },
  {
    id: 'p-long-003',
    title: 'Deepfake Detection Extension',
    slug: 'deepfake-detection',
    description: 'A browser extension to detect deepfakes on social media using GAN and diffusion-based detection models.',
    content: null,
    tags: ['security', 'ml', 'privacy'],
    image_url: null,
    demo_url: null,
    github_url: null,
    status: 'ongoing',
    contributors: null,
    is_published: true,
    created_at: '2025-10-05T00:00:00Z',
  },
]

export default LOCAL_PROJECTS
